映画登録画面の作成
hagitaku/movie_management pull request #11
Opened 2024-06-15 03:30 UTC by hokto

# このPRで達成したいこと
新たに映画の情報をユーザに登録させる

# このPRの内容を簡潔に
映画の情報を入力するフォームを簡易的に作成
タイトル，内容，メモを記入後に送信ボタンを押すとpostされ，その内容を取得する

# このPRにおける注意点(もしあれば)

2024-06-15 05:32 UTC, hagitaku commented
萩原メモ
* nodeのバージョンを聞き出す

2024-06-15 07:06 UTC, hagitaku requested changes

2024-06-15 07:06 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +export default function register(){
コンポーネントの定義は大文字で始まる
```suggestion
export default function Register(){
```

2024-06-15 07:06 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +export default function register(){
```suggestion
export const Register = () => {
```

2024-06-15 07:06 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +export default function register(){
基本functionは使わない

2024-06-15 07:06 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +    }
formのinputの要素を型定義しましょう
react hook formを使ってハンドラーとレジスターを渡してあげましょう

2024-06-15 07:06 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +                </div>
コンポーネント化しましょう!!

2024-06-15 07:06 UTC, hagitaku commented on frontend/projects/src/app/css/register.module.css
ディレクトリ構成をいい感じにしてください
テキストボックスをコンポーネント化する際に移動してください
テキストボックスは  `frontend/projects/src/app/component/form/TextBox` に定義してね

2024-06-15 07:06 UTC, hagitaku commented on frontend/projects/src/app/header.tsx
> +            </h1>
いらぬ

2024-06-15 07:08 UTC, hagitaku commented
次回TODO:
* fetcher定義
*

2024-06-17 14:18 UTC, hagitaku commented
まじでめちゃくちゃ今更で確認してなかった自分が本当に悪いんだけどサーバーコンポーネントとかクライアントコンポーネントとか言われてもわからないとかだったら早めに言って欲しいです
それによってfetcher定義の難易度が大きく違います

2024-06-23 12:46 UTC, hokto commented
反応すぐできなくてごめん
一応軽く調べてみたんだけどよく分からなかったからそこ含めて教えてくれると嬉しいです

2024-06-24 01:23 UTC, hagitaku commented
りょかい!!

2024-06-29 06:27 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +}
```suggestion
type TextBoxProps = {
    title: string;
    name: string;
}
```

2024-06-29 06:27 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +}
```suggestion
const TextBox = (props: TextBoxProps) => {

    const {
        name,
        title,
    } = props;

    return (
        <div className={style.form_group}>
            <label htmlFor={name}>{title}</label>
            <div className={style.form_input}>
                <input id={name} name={name} ></input>
            </div>
        </div>
    )
}
```

2024-06-29 06:27 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +    textBoxAreaCols: number;
任意の引数にしましょう
指定しない場合のデフォルト値を決定してあげましょう

```suggestion
    textBoxAreaRows?: number;
    textBoxAreaCols?: number;
```

2024-06-29 06:27 UTC, hagitaku commented on frontend/projects/src/app/layout.tsx
> +        {children}</body>
```suggestion
      <body className={inter.className}>
        <Header />
        {children}
      </body>
```

2024-06-29 06:56 UTC, hagitaku commented
get : useSWR
それ以外 : acxios

2024-06-29 07:11 UTC, hagitaku commented
https://nextjs-ja-translation-docs.vercel.app/docs/getting-started

2024-06-29 07:16 UTC, hagitaku commented
わからない状態が最高30分続いたら萩原に聞くように
基本は15分くらいで聞いても良い

2024-07-01 16:12 UTC, hagitaku reviewed
あとほんの少しです
指摘した点以外はapi叩くところですね
急ぎめで準備します

2024-07-01 16:12 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
registerを渡すようにしてしまうと、呼び出し元でregisterに指定するname属性をミスってしまう可能性があるので `form : UseFormReturn` を受け取るようにして、呼び出し元から渡されたnameをそのままregisterにわたすようにしてください

2024-07-01 16:12 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +};
コンポーネント間で値をやり取りするときに一時的に入れておくオブジェクトのことを`Props`と呼びます
ここではフォームの入力項目の型定義をしているので`Props`と命名するのは不適切です

2024-07-01 16:12 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +    const {register,handleSubmit} = useForm<RegisterProps>();
👍
指摘でもなんでもないただのコメントをします
この画面は登録画面なので不要ですが編集画面とかになるとdefaultValuesというパラメータを渡すことになります

2024-07-01 16:12 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +export default TextBoxArea;
非常に細かい指摘ですがファイルの終わりに改行を入れてください
その下になにか処理を追加したとき、ただ改行しただけなのに`export default TextBoxArea;`の行に差分が出ちゃいます

2024-07-02 07:30 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
> `form : UseFormReturn` を受け取るようにして、呼び出し元から渡されたnameをそのままregisterにわたすようにしてください

これやってみたら，`UseFormReturnには呼び出しシグネチャがありません．`って言われてうまくいかなかったので，UseFormRegisterReturnを使う実装でやってたんですけど，解決方法わかりませんか？

2024-07-02 07:50 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
よくわからないエラーです
これで行けませんか
```ts
import { UseFormReturn } from "react-hook-form";
import style from "./TextBox.module.css";

type TextBoxProps = {
    title: string;
    name: string;
    form: UseFormReturn;
};
const TextBox = (props: TextBoxProps) => {
    const {
        title,
        name,
        form,
    } = props;

    const { register } = form;

    return (
        <div className={style.form_group}>
            <label htmlFor={name}>{title}</label>
            <div className={style.form_input}>
                <input id={name} {...register(name)} type="text"></input>
            </div>
        </div>
    )
}
export default TextBox;

```

2024-07-02 09:07 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
上記の通り修正し，`register/page.tsx`で`<TextBox title="映画タイトル" name="movie_title" form={register}/>`としたところ，`register is not a function`を吐かれました．．．

2024-07-02 12:25 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
次の定例でみます

2024-07-02 16:02 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
chat-gptくんに聞きながらやってたら多分できました．
ずっと勘違いをしていて，TextBoxコンポーネントにregisterを渡さなければならないと思っていましたが，そうではなく`const form = UseForm()`としたformをTextBoxコンポーネントに渡して，その中でregisterを展開?して使用しなければならない，ということであってますか？

2024-07-02 16:08 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
そうそうそう！！！！
その通りです

2024-07-02 16:11 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
ありがとうございます！
そこちゃんと理解したことで実装ちゃんとかけました

2024-07-02 16:15 UTC, hokto commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +export default TextBoxArea;
了解です．
これについては他のものと合わせて修正して適宜コミットしていきます．

2024-07-02 16:28 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
最高です!
そんな感じです
じつは型パズルの大きな罠が仕掛けて本当はこんな感じです(これTypeScriptとreact hook formに慣れてないと無理なので今回は書いちゃいます)

TextBox.tsx ( TextBoxAreaも同様に)
```ts
import { UseFormReturn } from "react-hook-form";
import type { FieldValues, Path } from "react-hook-form";
import style from "./TextBox.module.css";

type TextBoxProps<T extends FieldValues> = {
    title: string;
    name: Path<T>;
    form: UseFormReturn<T>;
};
const TextBox = <T extends FieldValues>(props: TextBoxProps<T>) => {
    const {
        title,
        name,
        form,
    } = props;

    const { register } = form;

    return (
        <div className={style.form_group}>
            <label htmlFor={name}>{title}</label>
            <div className={style.form_input}>
                <input id={name} {...register(name)} type="text"></input>
            </div>
        </div>
    )
}
export default TextBox;
```
register\page.tsx
```ts
"use client"
import style from "./Register.module.css";
import { useForm } from "react-hook-form";
import TextBox from "../components/form/TextBox/TextBox";
import TextBoxArea from "../components/form/TextBoxArea/TextBoxArea";

type RegisterProps = {
    movieTitle: string;
    movieContents: string;
    movieMemo: string;
};
export const Register = () => {
    const form = useForm<RegisterProps>(); // ここ大事。React Hook Formが入力項目を識別するために必要
    const { handleSubmit } = form;
    const postRegisterForm = (formData: any) => {
        const {
            movieTitle,
            movieContents,
            movieMemo,
        } = formData;
        console.log("Title:", movieTitle);
        console.log("Contents:", movieContents);
        console.log("Memo:", movieMemo);
    }
    return (
        <main className={style.main}>
            <form className={style.form_group} onSubmit={handleSubmit(postRegisterForm)}>
                <TextBox title="映画タイトル" name="movieTitle" form={form} />
                <TextBoxArea title="映画情報" name="movieContents" form={form} />
                <TextBoxArea title="メモ" name="movieMemo" form={form} />
                <div className={style.form_btn}>
                    <button id="register_btn" type="submit">登録</button>
                </div>
            </form>
        </main>
    )
}
export default Register;

```

2024-07-02 16:30 UTC, hagitaku commented
もしvscodeを使用しているのであればESLintの拡張機能をいれることをおすすめします
いい感じにしてくれます

2024-07-04 14:26 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
ありがとうございます！
Pathとかは全くなんなのか知らないので，調べてみてわからなかったらまた聞きます．

2024-07-04 14:27 UTC, hokto commented
ESLint聞いたことあるけどなんとなく入れてなかったので，ちゃんと入れときます

2024-07-09 08:26 UTC, hokto commented on frontend/projects/src/app/register/page.tsx
> +};
これ，`RegisterInputDatas`とかはどうですか？
登録画面でのformの入力データ群という意味合いで

2024-07-09 08:33 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +};
登録画面でのformの入力データ群という意味合いなら非常に良いと思います
ただこの部分はフォームの入力項目の型定義であることに留意してください
萩原だったら`MovieRegistrationForm` とかにします

2024-07-09 08:36 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +};
まじで細かい指摘ですが、`Data`は実は複数形なのでデータ群、という意味でも`Data`で十分です
`Datas`は簡単に言うと`childrens`とか`teethes`みたいな感じです

2024-07-09 10:08 UTC, hokto commented on frontend/projects/src/app/register/page.tsx
> +};
なるほど，データ群というより型定義であることを明示するように命名した方が良さそうですね．
そっちの方を採用しようと思います．
`Data`が複数形なのは知識不足で知らなかったです．
ありがとございます．

2024-07-09 12:13 UTC, hokto commented on frontend/projects/src/app/register/page.tsx
> +};
今更ですけど，`Register`ってページ名を動詞で命名するのよくないですかね？
上のように`Registration`と名詞で命名した方がいいかなって思ったんですが，どうですか？

2024-07-09 12:17 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +};
個人的にはページ名は動詞で良いと思います
そのページでやりたいことが明確になります
参考までにAtCoderのユーザー登録画面は`https://atcoder.jp/register`です
強いて言うならcreateがいいな~くらいです

2024-07-09 12:18 UTC, hagitaku commented on frontend/projects/src/app/register/page.tsx
> +};
register -> 登録。認証を受ける印象が強い
create  -> これも登録だけど、作成に近い

2024-07-09 16:18 UTC, hokto commented on frontend/projects/src/app/register/page.tsx
> +};
なるほどー
じゃあページ名は可能な限り1動詞にした方が良さそうですね
`register`か`create`かについては，`register`はユーザ登録のイメージが強いので，今のうちに`create`に変更しようと思います．

2024-07-09 17:13 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +        register
上のsuggestを元にした修正内容です．
https://github.com/hagitaku/movie_management/pull/11/commits/2edbf3c54e40f037485a933469bc3831dab30662

2024-07-09 17:19 UTC, hokto commented on frontend/projects/src/app/register/page.tsx
> +};
とりあえずページ名を`Create`，フォームの入力項目の型定義についても`MovieCreationForm`に変更しました．
https://github.com/hagitaku/movie_management/pull/11/commits/7b749449ec016d55e736882c69eebbde906c6817

2024-07-15 11:00 UTC, hokto commented
今API処理の部分でformの内容をpostする部分をやってるんですが，frontend側からbackend側にpostするときのurlって`http://backend:8080/movie/register`であってますか？

2024-07-15 11:50 UTC, hagitaku commented
`http://backend:8080/movie/register`であってます
`BASE_URL_API`みたいなのとAPI固有のパスを定義して、`{BASE_URL_API}/{API_PATH}`みたいに結合してください

2024-07-15 12:08 UTC, hokto commented
了解です．
ただ，そのurlでpostしようとするとNetWorkError吐かれたんですよね．
色々調べた感じfrontendとbackendが同一ネットワーク上にいないっぽい?からダメみたいなんですが，こちらの環境の問題ですかね？

2024-07-15 12:09 UTC, hagitaku commented
確認してみます

2024-07-15 12:10 UTC, hagitaku commented
もし可能ならpostする処理をgitにあげていただけると検証が非常に楽です

2024-07-15 12:15 UTC, hokto commented
了解です．
今の段階までの分で上げます

2024-07-15 12:29 UTC, hagitaku commented
すみません
`http://backend:8080/movie/register`
ではなく
`http://127.0.0.1:8080/movie/register`
でした
あとCORSエラーが出るのでなにか対策が必要です
考えるのでフォームのリファクタなどをしてお待ち下さい

2024-07-15 12:47 UTC, hokto commented
了解です，その間にサイトの見た目を簡単に整えておきます．
ちなみにCORSエラーが出るのって，許可していないところからAPI叩かれるのを防ぐためって認識であってますか？

2024-07-15 12:48 UTC, hagitaku commented
そうです
許可したorigin外から適当なAPIを叩かれることを防ぐためにあります

2024-07-15 12:49 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +    form: UseFormReturn;
```suggestion
    form: UseFormReturn<T>;
```
ここも修正していただけると幸いです
多分これつけないと型エラーが出ると思います

2024-07-15 13:01 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +    form: UseFormReturn;
見逃してました
ありがとござます

2024-07-15 13:27 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +    form: UseFormReturn;
```suggestion
    form: UseFormReturn<T>;
```
ここも必要です

2024-07-15 13:35 UTC, hagitaku commented
対応しました
https://github.com/hagitaku/movie_management/pull/12

2024-07-16 04:54 UTC, hokto commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +    form: UseFormReturn;
すでに修正してcommitしてたんで上げました．
db8b021

2024-07-17 03:38 UTC, hokto commented
API処理について実装終わりました． c56d08a
また，コンポーネントごとにcssも書いたんですが，左に寄せる以外に何調整すべきかよくわからなかったので，何かあればお願いします． 4e745f3

2024-07-17 11:50 UTC, hagitaku commented
apiの実装遅れててすみません
スタイルについては適当でよいです
最低限のスタイルは要素の配置なのでそれさえ真っ当なものであれば問題ありません
本来であれば登録処理成功後の画面遷移をこのPRで実装したいですが、登録成功後に移動したい一覧画面が未実装なのでこのPRでは対応しないことにしましょう

2024-07-17 12:26 UTC, hagitaku commented
最終確認のレビューを依頼するのであればレビュワーズのところから再レビューを依頼してください

2024-07-17 13:20 UTC, hokto commented
りょかいです

2024-07-17 13:50 UTC, hagitaku commented on frontend/projects/src/app/components/form/Header/Header.tsx
> +            </h1>
この部分不要です

2024-07-17 13:50 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.module.css
> +.textBoxField{
命名規則が誤ってそうです
`text-box-field` が正しいです

2024-07-17 13:50 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +    )
指摘というわけではないです
`||` は左側がfalsyな場合に右側を返す演算子です
つまり、0などを入れてしまった場合、本当なら0を返してほしいのに右側の値を返してしまいます
```ts
 const a = 0;
 const b = a || 100;
 console.log(b); // 100 が出力される
```
`null`や`undefined`だけを弾きたい場合は`??`が適切です(今回のこのコンポーネントでは今の実装で問題ないです)

2024-07-17 13:50 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +            const BASE_API_URL = "http://127.0.0.1:8080/";
このページ限定の定数ではなく、プロジェクト全体の定数にしてください

2024-07-17 13:50 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +            console.log("Post Success:",response.data);
チャレンジするかはお任せします
対応しなくても良い課題です

APIを叩く関数をコンポーネント外で定義してください
ざっくり簡単に言うと

```tsx
// ファイル1 どのコンポーネントからも呼び出せるようにしておく ここらへんが参考になるかも https://zenn.dev/aiq_dev/articles/3bcfc7bb2b7c1a
// チャレンジ1 関数を別で定義
const postCreateMovie = (request : Request) => { // チャレンジ2 引数を型定義。型による縛りが発生して、流用&デバッグが楽になる
    // memo1 APIを叩く関数を別で定義することで、1つのAPIを複数の画面で叩くケースが出てきた場合、楽になる
    const response = axios.post(postUrl,request);
    // 必要ならエラーハンドリング
    return response;
}


// ファイル2 コンポーネント
const component = () =>{
    const form = useForm<ImputType>();
    // 実はSubmitHandlerという型を使用することで楽になります
    const handleSubmit :SubmitHandler<ImputType> = (formInput) =>{
        const request = {}; // 値を詰め込む
        const response = postCreateMovie (request);
        // もし必要ならレスポンスを使ったなにかの処理
    }

    return(
        <form onSubmit=handleSubmit >
                // ごにょごにょ
        </form>
    )
}
```

2024-07-17 13:50 UTC, hagitaku commented on frontend/projects/src/app/layout.tsx
> +//import "./globals.css";
不要ならコメントアウトではなく消しちゃいましょう

2024-07-18 01:23 UTC, hokto commented on frontend/projects/src/app/components/form/Header/Header.tsx
> +            </h1>
ごめんなさい

2024-07-18 01:25 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.module.css
> +.textBoxField{
この部分実は相談したいやつでした．
変更前の規則が変な気がしたので，変数名と同じ規則に合わせたのですが，idはidでまた別の規則を使用した方がいいんですかね？
idの命名に関する慣習とかがあったら教えて欲しいです．

2024-07-18 01:31 UTC, hokto commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +    )
なるほど
上手く言えるか分からないんですが，例えば，今回のケースでは`null`や`undefined`を除外するために`||`を入れたのですが，0などの偽の評価になるもの全体を弾いているように読めてしまうので，そこで認識の相違が出てしまう，みたいなことですかね

2024-07-18 01:36 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.module.css
> +.textBoxField{
ここら辺読めば完璧です
[qiita](https://qiita.com/super-mana-chan/items/68b72f2d525eea86141b#%E5%8D%98%E8%AA%9E%E3%82%92%E3%81%A4%E3%81%AA%E3%81%90%E3%81%A8%E3%81%8D%E3%81%AF-%E3%82%92%E4%BD%BF%E3%81%86)
仕様する単語はできるだけ揃えたいところですが、命名規則は別の方が良いです

2024-07-18 01:40 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +    )
今回のコードで認識の相違が出るかどうか、ですかね?
それは多分大丈夫です。多分。
`null`や`undefined`を除外するために`||`を入れるのは悪くないですが、`0`や空文字列`""` も除外されちゃうから挙動が変わるよ〜ってことを伝えたかったです
むしろ今回の実装は正しくて、`row`に`0`を入れたとしてもそれは除外されて欲しいです

2024-07-18 04:03 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/TextBox.module.css
> +.textBoxField{
めちゃ助かります！
ありがとございます．

2024-07-18 04:08 UTC, hokto commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
> +    )
なるほど，よく考えたら今回は0も除外しないとダメですねー
よくわかりました，ありがとうございます!

2024-07-18 06:09 UTC, hokto commented on frontend/projects/src/app/create/page.tsx
> +            const BASE_API_URL = "http://127.0.0.1:8080/";
グローバル化について，調べたら定数のみ記述するファイルを用意する方法とcontext APIを使用する方法の2種類が出てきたんですが，どっちを使用するべきとかあったりしますか？

2024-07-18 06:10 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +            const BASE_API_URL = "http://127.0.0.1:8080/";
定数のみを記述するファイルを用意でお願いします

2024-07-18 06:13 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +            const BASE_API_URL = "http://127.0.0.1:8080/";
[おまかせチャレンジ](https://github.com/hagitaku/movie_management/pull/11#discussion_r1681080856) のコメントにある[エイリアス](https://zenn.dev/aiq_dev/articles/3bcfc7bb2b7c1a)にすると綺麗ですね

2024-07-18 06:15 UTC, hokto commented on frontend/projects/src/app/create/page.tsx
> +            const BASE_API_URL = "http://127.0.0.1:8080/";
了解です，調べつつやってみます．
ありがとございます!

2024-07-18 13:57 UTC, hokto commented
チャレンジも含めて修正終わったので時間ある時にレビューお願いします．

2024-07-18 14:27 UTC, hagitaku reviewed
ナイスチャレンジです
後ほんの少しです
eslintかなにかでコードのフォーマットをしてほしいです

2024-07-18 14:27 UTC, hagitaku commented on frontend/projects/src/app/api/post.tsx
> +};
stringはプリミティブ型を使用しましょう
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types

2024-07-18 14:27 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +    const onSubmit : SubmitHandler<MovieCreationForm> = (submitForm : MovieCreationForm) =>{
命名は`handle〇〇`にしましょう
理由は、この記事がわかりやすいです
https://qiita.com/itinerant_programmer/items/0d5303394da8e6c5310b

2024-07-18 14:27 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +        <main className={style["main"]}>
mainタグはlayout.tsxに入れてしまって、ページごとに定義するのを省きましょう
統一感が出ます

2024-07-20 06:59 UTC, hagitaku commented on frontend/projects/src/app/layout.tsx
>      <html lang="en">
```suggestion
    <html lang="ja">
```

2024-07-20 06:59 UTC, hagitaku commented on frontend/projects/src/app/api/post.tsx
> +const postCreateForm = async (request : PostCreateMovieRequest) =>{
```suggestion
const postCreate = async (request : PostCreateMovieRequest) =>{
```

2024-07-20 06:59 UTC, hagitaku commented on frontend/projects/src/app/api/post.tsx
> +        return error;
```suggestion
        throw error;
```

2024-07-20 06:59 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/TextBox.tsx
> +    )
コンポーネントを返すとき、returnの1つ上は開けましょう
```suggestion
    const { register } = form;
    
    return(
        <div className={style["text-box-field"]}> 
            <label htmlFor={name}>{ title }</label>
            <div className={style["text-box-input"]}>
                <input id={name} {...register(name)} type="text"></input>
            </div>
        </div>
    )
```

2024-07-20 06:59 UTC, hagitaku commented on frontend/projects/src/app/constants/constants.tsx
ファイル名,拡張子,ディレクトリ構造を見直しましょう。わからなかったら萩原がやるので言ってください

2024-07-20 07:17 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBoxArea/TextBoxArea.tsx
TextAreaで!

2024-07-22 04:41 UTC, hokto commented
ディレクトリ構成と命名を中心に修正しました．
再レビューお願いします．

2024-07-22 05:01 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextArea/index.tsx
> +    return(
コンポーネントを返すとき、returnの1つ上は開けましょう

2024-07-22 05:01 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/index.tsx
> +    return(
コンポーネントを返すとき、returnの1つ上は開けましょう

2024-07-22 05:01 UTC, hagitaku commented on frontend/projects/src/app/constants/index.tsx
このファイルを`index.tsx`から`env/index.ts`に変更しましょう
`index.ts`を新規作成し、export * from `{新しく切ったディレクトリ}`みたいにしましょう

2024-07-22 05:01 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +    const handleSubmitCreateBtn: SubmitHandler<MovieCreationForm> = (submitForm: MovieCreationForm) => {
`Btn`のように省略しなくて良いです
例外として`id`のように一般的に省略形で使用されてるものとかは認めます

2024-07-22 05:07 UTC, hokto commented on frontend/projects/src/app/components/form/TextBox/index.tsx
> +    return(
見落としです
ごめんなさい

2024-07-22 05:08 UTC, hagitaku commented on frontend/projects/src/app/components/form/TextBox/index.tsx
> +    return(
あるあるです

2024-07-22 12:54 UTC, hokto commented on frontend/projects/src/app/create/page.tsx
> +    const handleSubmitCreateBtn: SubmitHandler<MovieCreationForm> = (submitForm: MovieCreationForm) => {
`button`もそのままでいいんですね，了解です．
大体の単語はそのまま書けばいいと思っておけば良さそうですか？

2024-07-22 12:55 UTC, hagitaku commented on frontend/projects/src/app/create/page.tsx
> +    const handleSubmitCreateBtn: SubmitHandler<MovieCreationForm> = (submitForm: MovieCreationForm) => {
基本的に単語は省略せずにそのまま書いてよいです

2024-07-22 12:56 UTC, hokto commented on frontend/projects/src/app/constants/index.tsx
これってまた別種の定数値を設定したい時には新しいディレクトリ切ってその中の`index.ts`に記述する，という認識であってますか？

2024-07-22 12:59 UTC, hagitaku commented on frontend/projects/src/app/constants/index.tsx
そうです
`constants/env/index.ts`を追加したときと同様に
`constants/{新しいやつ}/index.ts`に定数を定義して
`constants/index.ts` に `export * from {新しいやつ}` をすることになります

2024-07-22 13:05 UTC, hokto commented on frontend/projects/src/app/constants/index.tsx
りょかいです!

2024-07-22 13:06 UTC, hokto commented on frontend/projects/src/app/create/page.tsx
> +    const handleSubmitCreateBtn: SubmitHandler<MovieCreationForm> = (submitForm: MovieCreationForm) => {
了解です．
もし迷ったときは聞きます

2024-07-22 13:08 UTC, hagitaku approved these changes
LGTMです!
対応ありがとうございました
お疲れ様でした

2024-07-22 13:10 UTC, hokto commented
こちらこそ数々のレビューありがとうございましたー！

2024-07-22 13:11 UTC, merged